### PR TITLE
Dark mode update

### PR DESCRIPTION
**Pull request by jcontonio**
* Makes sure confirmation dialogs look good
* Makes sure data-fields look good
* Updates form field and other icons to all look the same

To test, open Safari devtools, click the dark mode button in the Elements tab, refresh the page, and click around

### CODE REVIEW

**Comment by dheniges** [comment]
@jcontonio reviewing, but there's a conflict in the css

**Comment by dheniges** [comment]
Updates look like they fixed things. Two things I noticed for dark mode:
Screen Shot 2019-11-27 at 3 40 09 PM
^ codemirror cursor is black, real hard to see

Screen Shot 2019-11-27 at 3 39 58 PM
^ icons have very little contrast with that dark background

**Comment by jcontonio** [comment]
@dheniges fixed, ready for review

**Review by dheniges — APPROVED** [review]
🎉 🌮

**Pull request merged**
