### PR TITLE
soft deleted user restore

### PR DESCRIPTION
**Pull request by jjidt**
we might have issues undoing the migration I added.  If there are items with null values in the database it will throw an error when trying to revert the allowNull constraint.

### CODE REVIEW

**Review by dheniges — COMMENTED** [review]
This works, I can add a user to the same org or a new org. Question on the migration: seems like it shouldn't be reversible, so should the down() just do nothing?

**Comment by jjidt** [comment]
yeah, that's what I was wondering, makes sense to me

**Comment by jjidt** [comment]
updated with an empty promise

**Review by dheniges — APPROVED** [review]
v. nice

**Pull request merged**
