### PR TITLE
UI – Page titles

### PR DESCRIPTION
**Pull request by jcontonio**
* Adds page titles
* Adding in react-helmet package to manage <meta> tags throughout the app
* Added <Helmet>'s to containers specifically, to keep them separate & obvious

`make installweb`

### CODE REVIEW

**Comment by dheniges** [comment]
@jcontonio conflict funtimes!

**Comment by jcontonio** [comment]
@dheniges fixed up

**Comment by dheniges** [comment]
The way this is setup it will keep the last page title set. Is there a way to set a default title with helmet that will get set if nothing else in the current render is updating the title?

For example, if I go to a document I see "Project Name: Document Name" which is cool. But then if I navigate to the user menu and go to settings, there's no page title set so it keeps the "Project Name: Document Name" title.

**Review by dheniges — APPROVED** [review]
We'll see what codefresh has to say, but looks good to me

**Pull request merged**
