### PR TITLE
Fixing draggable on document mode change

### PR DESCRIPTION
**Pull request by jcontonio**
This may help with the touch stuff too. Will merge release into that and test once this gets merged.

### CODE REVIEW

**Review by dheniges — CHANGES_REQUESTED** [review]
This fixes the issue with the data fields (string, number) but image fields are still drag'n'droppable. I dunno if that's a different issue though?

**Comment by jcontonio** [comment]
I think images are getting their regular drag and drop behavior from the OS. I will figure that out on this PR, but it is a separate issue.

**Comment by jcontonio** [comment]
Ok, this should finally be fixed.

**Review by dheniges — APPROVED** [review]
💯

**Pull request merged**
