### PR TITLE
Removing styles

### PR DESCRIPTION
**Pull request by jcontonio**
Removing any nice markdown formatting styles because it just ends up breaking stuff

### CODE REVIEW

**Review by dheniges — CHANGES_REQUESTED** [review]
The blockquote styling gets applied to the next line that's not a blockquote

Screen Shot 2020-02-10 at 4 52 09 PM

**Comment by jcontonio** [comment]
This will require this PR to be merged: https://github.com/BonkeyBong/CodeMirror/pull/1

Then you'll need to do an `npm install` in web to get the correct Bonkey version of CodeMirror.

**Review by dheniges — COMMENTED** [review]
Screen Shot 2020-02-21 at 10 21 55 AM

The problem is still there, the only way to get it to not apply the blockquote styling is to have a blank line between the last blockquote and the next line. It looks like a codemirror class getting applied to the line (`cm-quote`), so I dunno if there's anything to be done?

**Comment by dheniges** [comment]
also just confirmed the quote class is added in the older codemirror version too, it just wasn't styled gray so you couldn't tell in the UI

**Review by dheniges — APPROVED** [review]

**Pull request merged**
