### PR TITLE
field sync

### PR DESCRIPTION
**Pull request by jjidt**
- Adds field handling to sync server
- @jcontonio I need your help with this, I don't want to step on your md editor code ->
when a user updates a field, the event is successfully transmitted and data refetched by fellow room users, and even though the updated field is making it to the field component, the displayed field value isn't getting updated

### CODE REVIEW

**Comment by jjidt** [comment]
have this updating field display as its changed by another user, we should thoroughly test this on dev to make sure its not jacking the cursor position as you're working

**Comment by dheniges** [comment]
@jjidt merge conflict. womp womp

**Comment by jjidt** [comment]
updated

**Review by dheniges — APPROVED** [review]
I dunno if this is perfect, but it's fun to play around with therefore 👍 

But seriously we should do some joint QA like you mentioned JJ, but I think this is good to go into the feature branch

**Pull request merged**
