### PR TITLE
Bug – Changing to fetch user

### PR DESCRIPTION
**Pull request by jcontonio**
Switched to fetching the user, instead of looking at the loaded users

### CODE REVIEW

**Review by dheniges — CHANGES_REQUESTED** [review]
Refreshing on this page causes an error in the app

**Comment by jcontonio** [comment]
@dheniges not seeing that in any browser - any ideas?

**Comment by dheniges** [comment]
I see it in all browsers. It looks like it's because `userFromRoute` is not defined initially on refresh, and the other useDataService calls are trying to call `userFromRoute.id` on undefined

**Review by dheniges — APPROVED** [review]
:+1:

**Pull request merged**
