### PR TITLE
Mobile updates

### PR DESCRIPTION
**Pull request by jcontonio**
* Updates mobile views throughout the site
* Moves the "upgrade" notices out of the top header into its own subhead on mobile
* Makes sure we can have a home screen app that looks good

image

### CODE REVIEW

**Comment by jjidt** [comment]
I get stuck when going to create an initial document on iphone 6s:

IMG_1603

**Comment by jjidt** [comment]
IMG_B853C214A0A3-1

Delete icon is overlapping user reinvite link

**Comment by dheniges** [comment]
0EDC89F4-1ABF-4359-9374-84968B259B6C_1_105_c

The placeholder text for strings and numbers gets cutoff. And what JJ said about creating documents being broken.

Otherwise I think desktop is good, opened other issues as I found them

**Review by dheniges — APPROVED** [review]
Mobile!

**Pull request merged**
