### PR TITLE
Adding password meter

### PR DESCRIPTION
**Pull request by jcontonio**
* Adds client-side password checking
* Adds new Popover UI component
* Only loads zxcvbn when UserSecurity component gets loaded, so we don't have a giant library in the regular endpoint

### CODE REVIEW

**Review by jjidt — CHANGES_REQUESTED** [review]
Code looks good, there's some overlap that can happen with the dual popups

Screen Shot 2019-10-14 at 4 53 32 PM

**Comment by jjidt** [comment]
Also, go through the whole sign up flow, I wasn't seeing these for the initial password page

**Comment by jcontonio** [comment]
@jjidt pull the latest and all of those problems should be solved

**Review by jjidt — APPROVED** [review]
👍

**Pull request merged**
