### PR TITLE
password change

### PR DESCRIPTION
**Pull request by jjidt**
Password change, API and Web

@jcontonio wanna take a look at this first and see if you want to do anything in a different way?

### CODE REVIEW

**Comment by jcontonio** [comment]
Yep, will take a look @jjidt

**Comment by jcontonio** [comment]
image

We need errorDetails populated like all other validation things, so we can display a message with the field. I think something like password, newPassword, confirmPassword

**Comment by jcontonio** [comment]
btw I updated the branch to get the form to work with validation

**Comment by jjidt** [comment]
@jcontonio passing this back to add field validation

**Comment by jcontonio** [comment]
@jjidt ready for ya

**Review by jcontonio — APPROVED** [review]

**Pull request merged**
