### PR TITLE
soft delete

### PR DESCRIPTION
**Pull request by jjidt**
- updates id references in migration files
- moves org migration before user migration
- adds paranoid: true to all models which results in deletedAt timestamp being added to soft-deleted items

### CODE REVIEW

**Comment by jjidt** [comment]
oops, I broke all the tests ha

**Comment by jjidt** [comment]
locking in the id references exposed a bunch of false positives in the tests, all fixed up now

**Review by dheniges — COMMENTED** [review]
I tested deleting a lot of things and all seemed well 👍 

I looked around a bit and beyond ordering (which I'm working on, and will fix) I didn't see any custom querying. Any custom queries you can think of that will need to respect deleted resources?

**Comment by jjidt** [comment]
nope, I think ordering is all

**Review by dheniges — APPROVED** [review]
Stamp of Approval™

**Pull request merged**
