### PR TITLE
cancel subscription

### PR DESCRIPTION
**Pull request by jjidt**
- adds endpoint to cancel org account
- sets up a reusable function to grab the stripe status and update the cached data on the org
- adds additional hooks for updating subscription data

### CODE REVIEW

**Review by dheniges — CHANGES_REQUESTED** [review]
Code looks excellent considering the complexity 👍 

The checkActiveOrgStatus middleware needs updating to use the new ORG_SUBSCRIPTION_STATUS constants though I think. If you register a new org you'll see the errors because it's checking against the STRIPE_STATUS

**Comment by jjidt** [comment]
@dheniges updated, with the TRIALING_PENDING_ACTIVE status allowed too

**Review by dheniges — CHANGES_REQUESTED** [review]
Seed data needs updating to work with new ORG_SUBSCRIPTION_STATUS values too

**Review by dheniges — APPROVED** [review]
:+1:

**Pull request merged**
