### PR TITLE
Adds all new Document Panel

### PR DESCRIPTION
**Pull request by jcontonio**
* New document panel split up by tabs
* Edit document name and info, see updated dates
* Move to the outline, edit a field's settings from the outline or from the document
* Completely new field settings forms

@jjidt need help with getting the file input for image/file fields working. We'll want a status there while it's uploading.

## Known bugs

1. Document name doesn't change in the DocumentHeaderContainer when changing in the panel. List changes though

Screen Shot 2021-04-23 at 17 18 22

### CODE REVIEW

**Comment by dheniges** [comment]
Screen Shot 2021-04-26 at 11 23 26 AM

The drag and drop reordering in the outline isn't working. I'm in FF

**Comment by dheniges** [comment]
Screen Shot 2021-04-26 at 11 25 25 AM
Screen Shot 2021-04-26 at 11 25 34 AM

With the document outline above, when I click into the field editor pane of the outline, it says "Select a field to edit" which takes me back to the field outline. However, none of those fields are editable I guess?

**Comment by dheniges** [comment]
Screen Shot 2021-04-26 at 11 28 16 AM

This error triggered (and gives you the "Something went wrong" error page in react) when trying to edit an image field that presumably has null metadata.

**Review by jjidt — APPROVED** [review]
:dumps: 👍

**Pull request merged**
