### PR TITLE
fixing seat discrepencies on web

### PR DESCRIPTION
**Pull request by dheniges**
Basically, updating state.organization.seatsById to remove it when users are added or removed, and when org seats are changed on the plan.

Fixes all the issues I could find on web. Opening a new ticket for the fact you can create more users on the API than your plan allows

### CODE REVIEW

**Review by jjidt — CHANGES_REQUESTED** [review]
When I create a user and navigate back to the billing page the current seats aren't updated

**Comment by jcontonio** [comment]
Just went through, and yeah, that ^

Fixes the scenario I ran into earlier 👍

**Comment by dheniges** [comment]
The problem with the billing page is the user counts aren't updated on the org subscription when users are added or removed. That has to get fixed on the API, which is a separate ticket

**Comment by dheniges** [comment]
Ignore my previous comment. Forces refresh of org billing on user add/delete now

**Review by jjidt — APPROVED** [review]

**Pull request merged**
