### PR TITLE
Hiding plans

### PR DESCRIPTION
**Pull request by jcontonio**
* Updates plan language
* Hides plan selection for anyone that isn't SINGLE_USER
* Updates Form component disabled logic

### CODE REVIEW

**Comment by jcontonio** [comment]
Update plan features

All plans:

- Unlimited projects
- Unlimited documents
- Full API access with selectable access levels
- 10gb of storage

Multi-user Plan

- 5 users included
- $10/mo per additional user
- Project access control. Select who can view, contribute, or administer projects

**Review by dheniges — CHANGES_REQUESTED** [review]
The AdminNoticesComponent still has single-user/multi-user language based on trial status

Everything else looks good

**Comment by jcontonio** [comment]
@dheniges fixed, nice catch

**Review by dheniges — APPROVED** [review]
huzzah

**Pull request merged**
