### PR TITLE
add lastPublishedAt to documents

### PR DESCRIPTION
**Pull request by jjidt**

### CODE REVIEW

**Review by jcontonio — CHANGES_REQUESTED** [review]
We'll need to add lastPublishedAt in the return for document, documents, and publish endpoint returns. I've added the display in the client, but I'm not seeing the field on any network response after doing a migration.

**Review by jcontonio — DISMISSED** [review]
lol nevermind - I was on the wrong branch

**Review by jcontonio — APPROVED** [review]
Added published at UI

**Comment by jjidt** [comment]
CI failure on build stage, not tests, gonna merge

**Pull request merged**
