### PR TITLE
bump up default timeout and add extended timeout for PUT/POST

### PR DESCRIPTION
**Pull request by jjidt**
do we want either of these longer? can change if needed

### CODE REVIEW

**Review by jcontonio — DISMISSED** [review]
👍

**Comment by jjidt** [comment]
@jcontonio I'm gonna add some global error handling for timeout errors on this PR then have you check it out again

**Comment by jjidt** [comment]
@jcontonio updated with timeout error handling and global error handling in relevant actions

**Review by jcontonio — APPROVED** [review]
Hoooooray 👍

**Pull request merged**
