### PR TITLE
Project/Doc 404 handling on web

### PR DESCRIPTION
**Pull request by jjidt**

### CODE REVIEW

**Comment by jcontonio** [comment]
I tried the following and got the 404 page:
http://localhost:3000/d/project/110000/document/1200019191

I tried the following and didn't get the 404 page, but got the notification
http://localhost:3000/d/project/12

Renders the project, but oddly, and no 404
http://localhost:3000/d/project/undefined
http://localhost:3000/d/project/null

I think we should set up a route at the top level for the 404 page and redirect all of these cases there, instead of rendering the project view. Is this what you were talking about this morning? That a redirect is a problem?

**Comment by jjidt** [comment]
I'll give it a try with a top level 404 and see if the redirect still has issues

**Comment by jjidt** [comment]
@jcontonio was still having infinite loop issues, but found that returning a router Redirect component takes care of it, check out the behavior and see if it's along the lines you were thinking

**Comment by jcontonio** [comment]
Only thing I am seeing is http://localhost:3000/d/project/110000/document/asd doesn't return a 404 anymore, and no errors - the rest of the example URLs work, just not an invalid document id

**Comment by jjidt** [comment]
@jcontonio ready for more of that sweet sweet QA

**Comment by jcontonio** [comment]
Ok, after we chatted through this:

1. /project/blah -> render `/components/ProjectList/NoProject.js`
2. /project/110000/document/blah -> render `/components/Document/NoDocument.js`
3. anything else -> renders catch all 404 at top route (I pushed this up)

hopefully without any redirects or notifications

**Comment by jjidt** [comment]
ok, I think this is what we want now, ready for another look

**Comment by jjidt** [comment]
added the redirect from root to /projects to this PR to avoid conflicts

**Review by dheniges — COMMENTED** [review]
Scenarios I tested all work. @jcontonio do you want to style the 404s here or backlog that?

**Review by dheniges — APPROVED** [review]
👏

**Pull request merged**
