### PR TITLE
Fields fetch uses document instead

### PR DESCRIPTION
**Pull request by jcontonio**
* Removes request / receive FIELDS actions and fetching
* Switches documentFields reducer to use document receive action
* Needs updated document endpoint with values to work onload... getting everything on update, etc.

### CODE REVIEW

**Comment by dheniges** [comment]
holding off on this until there are field values on this endpoint so it doesn't break the app

**Comment by dheniges** [comment]
@jcontonio the documents endpoint has been updated with values now in master, but there's a conflict here

**Comment by jcontonio** [comment]
@jjidt this is ready for ya

**Review by jjidt — APPROVED** [review]
👍 looks good

I fixed the merge conflict
also fixed a bug with the fields list not updating when going from a single field to no fields

**Pull request merged**
