### PR TITLE
CRUD users

### PR DESCRIPTION
**Pull request by jjidt**

### CODE REVIEW

**Review by dheniges — COMMENTED** [review]
Code looks good. I'm going to wait for you to merge in the name update here and remove that TODO and test it out

**Comment by jjidt** [comment]
@dheniges updated

**Review by dheniges — COMMENTED** [review]
Functionality works as expected 👍 

For POST users though, there's no return. I would expect it to return the user that's created

**Comment by jjidt** [comment]
updated with user return

**Comment by jjidt** [comment]
ooh, should probably add that to the coordinator test

**Review by dheniges — APPROVED** [review]
Huzzah, users!

**Pull request merged**
