### PR TITLE
🎉 Drag and Drop Party 🎉

### PR DESCRIPTION
**Pull request by jcontonio**
* Adds new Photo field, with image preview, drag and drop
* Adds field moving prep - drag a field to another document (logs relevant info)
* Adds dragging and dropping of markdown files to the document list of a project, creates them with a body
* Adds body field to new document by default
* Focuses the last line of text in the document automatically
* Updates styling of the editor more

**Needs**
Update endpoint for the image field... images are not saving yet.

### CODE REVIEW

**Comment by jcontonio** [comment]
@jjidt when you get a sec, can you take a look at this? On line #22 of DocumentsListContainer.js, I can create a text field with a ` ` value, but not a `` value. Any way around that? 

I basically want to create an empty body field, so the placeholder appears in the textarea

**Comment by jjidt** [comment]
@jcontonio check if the changes I pushed up fix the problems you were having

**Comment by jcontonio** [comment]
It uploads 👍 thanks!
Working on the state change though, I had made some changes locally

**Review by jjidt — DISMISSED** [review]
👍 Works great in different browsers, great to see this coming together.  Also since the timeout hack is for UI weirdness I'm cool with it.

**Review by jjidt — APPROVED** [review]

**Pull request merged**
