### PR TITLE
Adding new icons

### PR DESCRIPTION
**Pull request by jcontonio**
New icons in place. Check out the ContentMenu and Settings / Admin sections for some new ones.

### CODE REVIEW

**Comment by dheniges** [comment]
Screen Shot 2019-10-29 at 1 00 51 PM
Looks like the `A,B,C` icon in the content menu thing has the `A` partially cutoff? Or is that supposed to do that?

**Comment by jcontonio** [comment]
> Screen Shot 2019-10-29 at 1 00 51 PM
> 
> Looks like the `A,B,C` icon in the content menu thing has the `A` partially cutoff? Or is that supposed to do that?

Fixed (with a temp fix)

**Comment by dheniges** [comment]
new icon looks good but now there's a conflict

**Comment by jcontonio** [comment]
Fixed

**Review by dheniges — APPROVED** [review]
🥇

**Pull request merged**
